apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-tensorboard
  labels:
    app: {{ .Values.appPrefix }}-tensorboard
spec:
  type: NodePort
  ports:
    - name: {{ .Values.appPrefix }}-tensorboard
      nodePort: {{ .Values.modelTraining.nodePort }}
      port: 6006
      protocol: TCP
      targetPort: 6006
  selector:
    app: {{ .Values.appPrefix }}-tensorboard
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-analytics
  labels:
    app: {{ .Values.appPrefix }}-analytics
spec:
  type: NodePort
  ports:
    - name: {{ .Values.appPrefix }}-analytics
      nodePort: {{ .Values.analyticService.nodePort }}
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ .Values.appPrefix }}-analytics
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appPrefix }}-user
  labels:
    app: {{ .Values.appPrefix }}-user
spec:
  type: NodePort
  ports:
    - name: {{ .Values.appPrefix }}-user
      nodePort: {{ .Values.analyticUser.nodePort }}
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: {{ .Values.appPrefix }}-user