# Default values for signal-pricing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appPrefix: signal-pricing

analyticService:
  nodeName:
  env:
    SYMBOL: NVDA
  imagePullSecrets:
    - ngc-secret
  nodePort: 30800
  pullPolicy: Always
  repository: registry.local:31500/signal-pricing-analytic-service
  resources:
    requests:
      cpu: 2500m
      memory: 8Gi

analyticUser:
  env:
    SYMBOL: NVDA
  imagePullSecrets:
    - ngc-secret
  nodePort: 30888
  pullPolicy: Always
  repository: registry.local:31500/signal-pricing-analytic-user
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: 2500m
      memory: 16Gi
    limits:
      cpu: 10000m
      memory: 32Gi

featureEngineering:
  env:
    ALPHA_VANTAGE_API_KEY: demo
    INTERVAL: 15min
    SYMBOL: NVDA
  imagePullSecrets:
    - ngc-secret
  pullPolicy: Always
  repository: registry.local:31500/signal-pricing-feature-engineering

imageCredentials:
  email: user@nvidia.com
  password: api-key
  registry: nvcr.io
  username: $oauthtoken

modelTraining:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.count
              operator: In
              values:
                - "2"
                - "4"
                - "8"
  resources:
    limits:
      nvidia.com/gpu: 2
  env:
    BATCH_SIZE: 512
    EPOCHS: 20
    LR: 1e-3
    NGPU: 2
    SEED: 1
    SYMBOL: NVDA
    TRAIN_SAMPLE: 64000
    VALIDATION_SAMPLE: 14000
  imagePullSecrets:
    - ngc-secret
  nodePort: 30600
  pullPolicy: Always
  repository: registry.local:31500/signal-pricing-model-training
  tensorboardImage: nvcr.io/nvidia/tensorflow:21.12-tf2-py3

persistentVolume:
  path: /volume1/brandon/signal-pricing
  server: 192.168.1.232
  storage: 128Gi